/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{svelte,js,html}"],
  theme: {
    extend: {
      colors: {
        base: {
          1: "var(--base-1)",
          2: "var(--base-2)",
          3: "var(--base-3)",
          4: "var(--base-4)",
          5: "var(--base-5)",
          6: "var(--base-6)",
          7: "var(--base-7)",
          8: "var(--base-8)",
          9: "var(--base-9)",
          10: "var(--base-10)",
          11: "var(--base-11)",
          12: "var(--base-12)",
        },
        brand: {
          1: "hsl(var(--brand-1) / <alpha-value>)",
          2: "hsl(var(--brand-2) / <alpha-value>)",
          3: "hsl(var(--brand-3) / <alpha-value>)",
          4: "hsl(var(--brand-4) / <alpha-value>)",
          5: "hsl(var(--brand-5) / <alpha-value>)",
          6: "hsl(var(--brand-6) / <alpha-value>)",
          7: "hsl(var(--brand-7) / <alpha-value>)",
          8: "hsl(var(--brand-8) / <alpha-value>)",
          9: "hsl(var(--brand-9) / <alpha-value>)",
          10: "hsl(var(--brand-10) / <alpha-value>)",
          11: "hsl(var(--brand-11) / <alpha-value>)",
          12: "hsl(var(--brand-12) / <alpha-value>)",
        },
        blue: {
          1: "hsl(var(--blue-1) / <alpha-value>)",
          2: "hsl(var(--blue-2) / <alpha-value>)",
          3: "hsl(var(--blue-3) / <alpha-value>)",
          4: "hsl(var(--blue-4) / <alpha-value>)",
          5: "hsl(var(--blue-5) / <alpha-value>)",
          6: "hsl(var(--blue-6) / <alpha-value>)",
          7: "hsl(var(--blue-7) / <alpha-value>)",
          8: "hsl(var(--blue-8) / <alpha-value>)",
          9: "hsl(var(--blue-9) / <alpha-value>)",
          10: "hsl(var(--blue-10) / <alpha-value>)",
          11: "hsl(var(--blue-11) / <alpha-value>)",
          12: "hsl(var(--blue-12) / <alpha-value>)",
        },
        green: {
          1: "hsl(var(--green-1) / <alpha-value>)",
          2: "hsl(var(--green-2) / <alpha-value>)",
          3: "hsl(var(--green-3) / <alpha-value>)",
          4: "hsl(var(--green-4) / <alpha-value>)",
          5: "hsl(var(--green-5) / <alpha-value>)",
          6: "hsl(var(--green-6) / <alpha-value>)",
          7: "hsl(var(--green-7) / <alpha-value>)",
          8: "hsl(var(--green-8) / <alpha-value>)",
          9: "hsl(var(--green-9) / <alpha-value>)",
          10: "hsl(var(--green-10) / <alpha-value>)",
          11: "hsl(var(--green-11) / <alpha-value>)",
          12: "hsl(var(--green-12) / <alpha-value>)",
        },
        red: {
          1: "hsl(var(--red-1) / <alpha-value>)",
          2: "hsl(var(--red-2) / <alpha-value>)",
          3: "hsl(var(--red-3) / <alpha-value>)",
          4: "hsl(var(--red-4) / <alpha-value>)",
          5: "hsl(var(--red-5) / <alpha-value>)",
          6: "hsl(var(--red-6) / <alpha-value>)",
          7: "hsl(var(--red-7) / <alpha-value>)",
          8: "hsl(var(--red-8) / <alpha-value>)",
          9: "hsl(var(--red-9) / <alpha-value>)",
          10: "hsl(var(--red-10) / <alpha-value>)",
          11: "hsl(var(--red-11) / <alpha-value>)",
          12: "hsl(var(--red-12) / <alpha-value>)",
        },
        orange: {
          1: "hsl(var(--orange-1) / <alpha-value>)",
          2: "hsl(var(--orange-2) / <alpha-value>)",
          3: "hsl(var(--orange-3) / <alpha-value>)",
          4: "hsl(var(--orange-4) / <alpha-value>)",
          5: "hsl(var(--orange-5) / <alpha-value>)",
          6: "hsl(var(--orange-6) / <alpha-value>)",
          7: "hsl(var(--orange-7) / <alpha-value>)",
          8: "hsl(var(--orange-8) / <alpha-value>)",
          9: "hsl(var(--orange-9) / <alpha-value>)",
          10: "hsl(var(--orange-10) / <alpha-value>)",
          11: "hsl(var(--orange-11) / <alpha-value>)",
          12: "hsl(var(--orange-12) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
